<?php

namespace App\Domain\Rules;

use App\Models\Alert;
use App\Models\CorrectiveAction;
use App\Models\MonitoringRule;
use App\Models\Project;
use Illuminate\Support\Facades\Log;

class MonitoringRulesEngine
{
    /**
     * Evaluate active monitoring rules against a project and generate alerts/actions.
     */
    public function evaluateRules(Project $project): array
    {
        $rules = MonitoringRule::where('is_active', true)
            ->where(function ($query) use ($project) {
                $query->whereNull('organization_id')
                    ->orWhere('organization_id', $project->organization_id);
            })
            ->get();

        $triggeredAlerts = [];

        foreach ($rules as $rule) {
            if ($this->matchesConditions($project, $rule->conditions)) {
                $alert = $this->executeRuleActions($project, $rule);
                if ($alert) {
                    $triggeredAlerts[] = $alert;
                }
            }
        }

        return $triggeredAlerts;
    }

    /**
     * Evaluate rule conditions JSON against project properties.
     */
    public function matchesConditions(Project $project, array $conditions): bool
    {
        foreach ($conditions as $cond) {
            $field = $cond['field'] ?? null;
            $operator = $cond['operator'] ?? '=';
            $targetValue = $cond['value'] ?? null;

            $actualValue = match ($field) {
                'overall_progress' => (float) $project->overall_progress,
                'health_status' => $project->health_status,
                'schedule_variance_days' => (int) ($project->custom_fields['schedule_variance_days'] ?? 0),
                'open_issues_count' => $project->issues()->whereIn('status', ['OPEN', 'IN_PROGRESS'])->count(),
                default => null,
            };

            if (!$this->compareValues($actualValue, $operator, $targetValue)) {
                return false;
            }
        }

        return true;
    }

    /**
     * Compare actual value vs target value using operators.
     */
    private function compareValues(mixed $actual, string $operator, mixed $target): bool
    {
        return match ($operator) {
            '=' => $actual == $target,
            '!=' => $actual != $target,
            '>' => $actual > $target,
            '<' => $actual < $target,
            '>=' => $actual >= $target,
            '<=' => $actual <= $target,
            'contains' => is_string($actual) && str_contains($actual, (string) $target),
            'in' => is_array($target) && in_array($actual, $target),
            'between' => is_array($target) && count($target) === 2 && $actual >= $target[0] && $actual <= $target[1],
            default => false,
        };
    }

    /**
     * Execute rule action payload (e.g. CREATE_ALERT, RECOMMEND_ACTION).
     */
    private function executeRuleActions(Project $project, MonitoringRule $rule): ?Alert
    {
        $actions = $rule->actions;
        $alert = null;

        if (isset($actions['create_alert'])) {
            $alertConfig = $actions['create_alert'];
            $alert = Alert::create([
                'project_id' => $project->id,
                'severity' => $alertConfig['severity'] ?? 'WARNING',
                'alert_type' => $rule->name,
                'message' => $alertConfig['message'] ?? "Rule '{$rule->name}' triggered for project {$project->name}.",
            ]);
        }

        if (isset($actions['recommend_action'])) {
            $actionConfig = $actions['recommend_action'];
            CorrectiveAction::create([
                'project_id' => $project->id,
                'alert_id' => $alert?->id,
                'title' => $actionConfig['title'] ?? "Recommended Action for {$rule->name}",
                'description' => $actionConfig['description'] ?? 'Automated recommendation generated by UPME Rules Engine.',
                'status' => 'RECOMMENDED',
            ]);
        }

        return $alert;
    }
}
